#pragma once

#ifdef CRT0_EXTRA_CORES_NUMBER
#undef CRT0_EXTRA_CORES_NUMBER
#endif
#define CRT0_EXTRA_CORES_NUMBER 1

#define WS2812_LED_COUNT_2 5
#define WS2812_DI_PIN_2 18

#define WS2812_MATRIX_STRING 0
#define STATUS_WS2812_MATRIX_STRING 1

#define LED_NO_INIT

#define LED_NUM_LOCK_STRING 2
#define LED_CAPS_LOCK_STRING 4
#define LED_SCROLL_LOCK_STRING 3

#define LED_STATUS_COLOR RGB_CYAN

#define SERIAL_USART_FULL_DUPLEX

#define SWITCH_OUTPUT
#define SWITCH_MASTER
